name: goreleaser

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: WillAbides/setup-go-faster@v1.14.0
        with:
          go-version-file: "go.mod"

      - name: Make All
        run: |
          ./package.sh
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          # either 'goreleaser' (default) or 'goreleaser-pro'
          distribution: goreleaser
          version: latest
          args: release --clean
          # workdir: ./cmd/frps_allowed_ports
        env:
          GITHUB_TOKEN: ${{ secrets.GPR_TOKEN }}